services:
  preprocess:
    image: prostate-segmentation:latest
    container_name: preprocess
    volumes:
      - ./data:/app/data
    command: python src/dataset/preprocess.py

  trainer:
    image: prostate-segmentation:latest
    container_name: trainer
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    volumes:
      - ./data:/app/data
      - ./Experiments:/app/Experiments
      - ./mlruns:/app/mlruns
      - ./configs:/app/configs
    depends_on:
      - mlflow
    command: python src/train/run.py

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: mlflow ui --host 0.0.0.0 --port 5000
